# docker-compose.yml
---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /home/data/.plex:/config
      - /home/data/minidlna:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_CLAIM="nope"
      - PUID=${PUID}
      - PGID=${PGID}

  nextcloud:  
    image: nextcloud
    container_name: nextcloud
    volumes:
      - /home/data/nextcloud:/var/www/html
    ports:
      - 9080:80
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

